"""create task status history table

Revision ID: 0b3eb2bd5ddb
Revises: 968e00cd1979
Create Date: 2026-09-07 09:54:39.925420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b3eb2bd5ddb'
down_revision: Union[str, Sequence[str], None] = '968e00cd1979'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_status_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('from_status', sa.String(length=50), nullable=False),
    sa.Column('to_status', sa.String(length=50), nullable=False),
    sa.Column('changed_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_status_history_changed_by'), 'task_status_history', ['changed_by'], unique=False)
    op.create_index(op.f('ix_task_status_history_id'), 'task_status_history', ['id'], unique=False)
    op.create_index(op.f('ix_task_status_history_task_id'), 'task_status_history', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_status_history_task_id'), table_name='task_status_history')
    op.drop_index(op.f('ix_task_status_history_id'), table_name='task_status_history')
    op.drop_index(op.f('ix_task_status_history_changed_by'), table_name='task_status_history')
    op.drop_table('task_status_history')
    # ### end Alembic commands ###
