"""preserve task activity on task deletion

Revision ID: 968e00cd1979
Revises: e62038679b11
Create Date: 2026-09-02 10:43:58.761187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '968e00cd1979'
down_revision: Union[str, Sequence[str], None] = 'e62038679b11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task_activities', 'task_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('task_activities_task_id_fkey'), 'task_activities', type_='foreignkey')
    op.create_foreign_key(None, 'task_activities', 'tasks', ['task_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task_activities', type_='foreignkey')
    op.create_foreign_key(op.f('task_activities_task_id_fkey'), 'task_activities', 'tasks', ['task_id'], ['id'])
    op.alter_column('task_activities', 'task_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
