"""create task activities table

Revision ID: e62038679b11
Revises: 86d69e58babf
Create Date: 2026-09-02 09:00:45.666940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e62038679b11'
down_revision: Union[str, Sequence[str], None] = '86d69e58babf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_activities_id'), 'task_activities', ['id'], unique=False)
    op.create_index(op.f('ix_task_activities_task_id'), 'task_activities', ['task_id'], unique=False)
    op.create_index(op.f('ix_task_activities_user_id'), 'task_activities', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_activities_user_id'), table_name='task_activities')
    op.drop_index(op.f('ix_task_activities_task_id'), table_name='task_activities')
    op.drop_index(op.f('ix_task_activities_id'), table_name='task_activities')
    op.drop_table('task_activities')
    # ### end Alembic commands ###
